param(
    [string]$OutputPath = "assets/models/test_city.obj"
)

$ErrorActionPreference = "Stop"

$OutputDir = Split-Path $OutputPath
if ($OutputDir) {
    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Montpellier Game generated test city OBJ")
$lines.Add("# Generated by scripts/generate_test_city_obj.ps1")

$vertexIndex = 1

function Add-Cube {
    param(
        [float]$Cx,
        [float]$Cy,
        [float]$Cz,
        [float]$Sx,
        [float]$Sy,
        [float]$Sz
    )

    $x0 = $Cx - $Sx / 2.0
    $x1 = $Cx + $Sx / 2.0
    $y0 = $Cy - $Sy / 2.0
    $y1 = $Cy + $Sy / 2.0
    $z0 = $Cz - $Sz / 2.0
    $z1 = $Cz + $Sz / 2.0

    $base = $script:vertexIndex

    $vertices = @(
        @($x0, $y0, $z0), @($x1, $y0, $z0), @($x1, $y1, $z0), @($x0, $y1, $z0),
        @($x0, $y0, $z1), @($x1, $y0, $z1), @($x1, $y1, $z1), @($x0, $y1, $z1)
    )

    foreach ($v in $vertices) {
        $script:lines.Add(("v {0:0.###} {1:0.###} {2:0.###}" -f $v[0], $v[1], $v[2]))
    }

    $faces = @(
        @(1, 2, 3), @(1, 3, 4), # front
        @(5, 7, 6), @(5, 8, 7), # back
        @(1, 5, 6), @(1, 6, 2), # bottom
        @(4, 3, 7), @(4, 7, 8), # top
        @(2, 6, 7), @(2, 7, 3), # right
        @(1, 4, 8), @(1, 8, 5)  # left
    )

    foreach ($f in $faces) {
        $a = $base + $f[0] - 1
        $b = $base + $f[1] - 1
        $c = $base + $f[2] - 1
        $script:lines.Add("f $a $b $c")
    }

    $script:vertexIndex += 8
}

for ($x = -3; $x -le 3; $x++) {
    for ($z = -3; $z -le 3; $z++) {
        if ($x -eq 0 -or $z -eq 0) { continue }
        if ((($x + $z) % 4) -eq 0) { continue }

        $height = 1.5 + (($x * $x + $z * $z) % 6)
        $width = 1.6 + (([Math]::Abs($x)) % 3) * 0.3
        $depth = 1.6 + (([Math]::Abs($z)) % 3) * 0.3

        Add-Cube `
            -Cx ($x * 4.0) `
            -Cy ($height / 2.0) `
            -Cz ($z * 4.0) `
            -Sx $width `
            -Sy $height `
            -Sz $depth
    }
}

Set-Content -Path $OutputPath -Value $lines -Encoding ASCII

Write-Host "OBJ généré : $OutputPath"
Write-Host "Vertices : $($vertexIndex - 1)"
