param(
    [string]$OutputPath = "assets/models/test_city.obj"
)

$ErrorActionPreference = "Stop"

$InvariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

function Format-Float {
    param([double]$Value)
    return $Value.ToString("0.###", $InvariantCulture)
}

$OutputDir = Split-Path $OutputPath
if ($OutputDir) {
    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
}

$CollisionPath = [System.IO.Path]::ChangeExtension($OutputPath, ".collisions.txt")

$lines = New-Object System.Collections.Generic.List[string]
$collisionLines = New-Object System.Collections.Generic.List[string]

$lines.Add("# Montpellier Game generated test city OBJ")
$lines.Add("# Generated by scripts/generate_test_city_obj.ps1")

$collisionLines.Add("# Montpellier Game collision sidecar")
$collisionLines.Add("# Format: box cx cy cz sx sy sz")

$vertexIndex = 1

function Add-Cube {
    param(
        [double]$Cx,
        [double]$Cy,
        [double]$Cz,
        [double]$Sx,
        [double]$Sy,
        [double]$Sz
    )

    $script:collisionLines.Add(
        "box $(Format-Float $Cx) $(Format-Float $Cy) $(Format-Float $Cz) $(Format-Float $Sx) $(Format-Float $Sy) $(Format-Float $Sz)"
    )

    $x0 = $Cx - $Sx / 2.0
    $x1 = $Cx + $Sx / 2.0
    $y0 = $Cy - $Sy / 2.0
    $y1 = $Cy + $Sy / 2.0
    $z0 = $Cz - $Sz / 2.0
    $z1 = $Cz + $Sz / 2.0

    $base = $script:vertexIndex

    $vertices = @(
        @($x0, $y0, $z0), @($x1, $y0, $z0), @($x1, $y1, $z0), @($x0, $y1, $z0),
        @($x0, $y0, $z1), @($x1, $y0, $z1), @($x1, $y1, $z1), @($x0, $y1, $z1)
    )

    foreach ($v in $vertices) {
        $script:lines.Add("v $(Format-Float $v[0]) $(Format-Float $v[1]) $(Format-Float $v[2])")
    }

    $faces = @(
        @(1, 2, 3), @(1, 3, 4),
        @(5, 7, 6), @(5, 8, 7),
        @(1, 5, 6), @(1, 6, 2),
        @(4, 3, 7), @(4, 7, 8),
        @(2, 6, 7), @(2, 7, 3),
        @(1, 4, 8), @(1, 8, 5)
    )

    foreach ($f in $faces) {
        $a = $base + $f[0] - 1
        $b = $base + $f[1] - 1
        $c = $base + $f[2] - 1
        $script:lines.Add("f $a $b $c")
    }

    $script:vertexIndex += 8
}

for ($x = -3; $x -le 3; $x++) {
    for ($z = -3; $z -le 3; $z++) {
        if ($x -eq 0 -or $z -eq 0) { continue }
        if ((($x + $z) % 4) -eq 0) { continue }

        $height = 1.5 + (($x * $x + $z * $z) % 6)
        $width = 1.6 + (([Math]::Abs($x)) % 3) * 0.3
        $depth = 1.6 + (([Math]::Abs($z)) % 3) * 0.3

        Add-Cube `
            -Cx ($x * 4.0) `
            -Cy ($height / 2.0) `
            -Cz ($z * 4.0) `
            -Sx $width `
            -Sy $height `
            -Sz $depth
    }
}

Set-Content -Path $OutputPath -Value $lines -Encoding ASCII
Set-Content -Path $CollisionPath -Value $collisionLines -Encoding ASCII

Write-Host "OBJ généré : $OutputPath"
Write-Host "Sidecar collisions : $CollisionPath"
Write-Host "Vertices : $($vertexIndex - 1)"
Write-Host "Boîtes collision : $($collisionLines.Count - 2)"

Write-Host ""
Write-Host "Aperçu sidecar :"
Get-Content $CollisionPath -TotalCount 6
